### ISSUE TITLE
[Feature] Implement an easy to use network request manager

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE-App-Components#17]
This network request manager helper class needs an implementation for that is common across the .NET platforms which attempts to make it easier to implement the ability of getting data from web APIs with a network request model. 

The implementation will be a part port from the WinUX app toolkit with improvements being made, for example, the caching of network responses for offline capabilities.

**Comment by jamesmcroft** [comment]
The components from the WinUX app toolkit should now all be in. Just needs validating.

**Comment by jamesmcroft** [comment]
Happy that the components here are completely ported and verified.

**Comment by tom-made** [comment]
@jamesmcroft going to re-open this and can be re-added to the project.

**Comment by jamesmcroft** [comment]
Another quick win, I'll sort this out later this evening.

**Comment by tom-made** [comment]
Happy to close this off. Thanks @jamesmcroft
