### ISSUE TITLE
Improve file data caching with encryption

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE-App-Components#19]
The current file system data caching mechanism is simple and writes out the data it stores into files which can be read easily. 

It would be a good idea to implement encryption and decryption of the data stored.

**Comment by jamesmcroft** [comment]
I've been thinking about this and we can either take advantage of already available libraries or could be incorporated as a feature in the XPlat Windows libraries.

**Comment by tom-made** [comment]
I was going to recommend using [PCLCrypto](https://github.com/AArnott/PCLCrypto) mainly because it's one we've used before.
