### ISSUE TITLE
[Feature] MvvmLight support for page navigation

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE-App-Components#31]
**Is your feature request related to a problem? Please describe.**

Given that MVVM is a common pattern for developing applications, it would be great to start developing easy to use components for building MVVM based pages on top of the current page navigation code.

**Describe the solution you'd like**
Using MvvmLight, in the first instance, we will create a MVVM friendly page with a base page view-model for handling the common page navigation calls, i.e. OnNavigatedTo.

**Comment by tom-made** [comment]
Merged the changes for the initial PR. Still requires implementations for iOS.

**Comment by jamesmcroft** [comment]
We're going to close this off in favor of providing an implementation using the Windows Community Toolkit MVVM framework 😄
