### ISSUE TITLE
[Feature] Make it easier to create custom controls

### ISSUE THREAD

**Issue by tom-made** [MADE-Apps/MADE-App-Components#32]
**Is your feature request related to a problem? Please describe.**

Building custom controls is not easy, even for those who are experienced at it. It would be great to have a solution that makes it easier to develop them.

**Describe the solution you'd like**
I propose that we develop a common way for creating custom controls using a base control inheriting from a platform specific one with additional properties and events.

**Additional context**
Before the reshuffle, we had similar code in our project already for doing this. It should be an easy port.

**Comment by tom-made** [comment]
As mentioned, @jamesmcroft we previously had some code in our previous structure which handles this. Would be great to just port this over.

**Comment by jamesmcroft** [comment]
Should be an easy one. I'll get this sorted ASAP

**Comment by tom-made** [comment]
Believe all the work is done on this now! Let's get cracking with those new controls
