### ISSUE TITLE
[Port] Make XPlat API library part of MADE

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE-App-Components#34]
**Is your feature request related to a problem? Please describe.**
After discussing with @tom-made, I feel that it might be worthwhile moving the XPlat Windows APIs into the MADE App Components library. This will hopefully make it easier for developers to use it and keep it updated. 

**Describe the solution you'd like**
The XPlat Windows APIs will be moved across to MADE taking on a new project name and namespace, while still keeping the Windows API naming convention.

**Comment by tom-made** [comment]
Great! Look forward to seeing this come across. Let me know if you need any help!

**Comment by jamesmcroft** [comment]
@tom-made it should be pretty easy to port across. The only difference is multi-targeting but I can work through that. It might mean some changes to the existing XPlat APIs to work in this structure.

**Comment by jamesmcroft** [comment]
After private discussion, this work will not continue. XPlat will remain a separate entity focussed on delivering Windows-like APIs for cross-platform development.
