### ISSUE TITLE
[Bug] JSON network requests cannot be created in common layer running on UWP due to namespace difference

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE-App-Components#40]
**Describe the bug**
The JSON network requests that were added to the project don't completely work in a UWP project when they are constructed from a .NET Standard 2.0 library as the constructor used does not exist for UWP.

**To reproduce in an app**
1. Add the MADE.App.Networking library to a UWP project and referenced .NET Standard 2.0 library.
2. Create a class in the .NET Standard 2.0 library that initializes a GET JSON network request.
3. Call the code from the class from a class in the UWP project
4. Run the app
5. When the code is executed, an exception is thrown because a constructor for the .NET Standard parameters does not exist for the UWP variant.

**Expected behavior**
The JSON network request should be constructed successfully and executed as expected.

** App (please complete the following information):**
 - Platform: Windows
 - Device: Surface Pro 4
 - Platform version: Windows 10 April 2018 Update
 - MADE version: 0.1.18171.1

**Comment by tom-made** [comment]
Thanks for fixing this @jamesmcroft

**Comment by jamesmcroft** [comment]
No worries @tom-made. Needed these fixes for a project I'm working on using MADE.
