### ISSUE TITLE
[Feature] Add support for a header text entry control (Xamarin.Forms)

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE-App-Components#48]
**Describe the solution you'd like**
At present, the Entry control in Xamarin.Forms uses the appropriate controls from each platform to enter text into a field. However, they don't take advantage of the header property.

This change would see a new control added to MADE to support a basic headered text entry control for Xamarin.Forms.

**Describe alternatives you've considered**
At the moment, you need to use a Label and Entry control together to achieve this solution.

**Comment by jamesmcroft** [comment]
This has been merged in now thanks to changes from @Tarc94 😄

**Comment by jamesmcroft** [comment]
Re-opening this issue. The control meets a minimum standard but isn't very customizable at the moment.

**Comment by Tarc94** [comment]
What other features would you like to see added for this?

**Comment by jamesmcroft** [comment]
I think this would be good for now. We can open up more in the future for other work. Thanks for the contribution.
