### ISSUE TITLE
Improvement to application diagnostics

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE-App-Components#52]
**Is your feature request related to a problem? Please describe.**
I've come up with two improvements that can be made to the application diagnostics components.

Firstly, there's no way to have a custom file name or log folder name for the EventLogger component. There may be a requirement where the log needs to be a specific file name or type in a specific application folder.

Secondly, when an exception is observed by the AppDiagnostics component, there is no way to know if that has happened apart from the event logging. There should be a way to bubble up the exception when it has been observed in case something else would like to know of the exception.

**Describe the solution you'd like**
For the first part, change the constant strings which declare the file and folder name to properties which can be set manually to alter the variables.

For the second, I recommend adding an event to the AppDiagnostics component which allows others to hook onto it. When an exception is observed as part of the AppDiagnostics, it would then pass the observed exception off through the event handler.

**Comment by tom-made** [comment]
Closing this off as the work is complete. Thanks @jamesmcroft
